#!/bin/bash

CWD=$(dirname $(readlink -f $0))

# Make sure our script is only being run with root privileges
if [ "$(id -u)" != "0" ];
then
   echo "Error: This script must be run with root privileges." 1>&2
   exit 1
fi

TL_NAME=AVTGigETL
PROFILE_FOLDER=/etc/profile.d
TL_SCRIPT_32BIT=${PROFILE_FOLDER}/${TL_NAME}_32bit.sh
TL_SCRIPT_64BIT=${PROFILE_FOLDER}/${TL_NAME}_64bit.sh

TL_PATH_32BIT=$CWD/CTI/x86_32bit
TL_PATH_64BIT=$CWD/CTI/x86_64bit

echo "Registering GENICAM_GENTL32_PATH"
printf "#!/bin/bash\n\n#Do not edit this file manually because it may be overwritten automatically.\nexport GENICAM_GENTL32_PATH=\$GENICAM_GENTL32_PATH:\"%s\"" $TL_PATH_32BIT > $TL_SCRIPT_32BIT
chmod +x $TL_SCRIPT_32BIT

if [ $(uname -m | grep '64') ];
then
	echo "Registering GENICAM_GENTL64_PATH"
	printf "#!/bin/bash\n\n#Do not edit this file manually because it may be overwritten automatically.\nexport GENICAM_GENTL64_PATH=\$GENICAM_GENTL64_PATH:\"%s\"" $TL_PATH_64BIT > $TL_SCRIPT_64BIT
	chmod +x $TL_SCRIPT_64BIT
fi
echo "Done"
echo "Please log off once before using the GENTL_PATH"
